#!/bin/bash
# vim: ft=bash foldlevel=99

function getVolume {
    wpctl get-volume @DEFAULT_SINK@ |
        sed -E -e 's/Volume: //' -e 's/ /\n/' \
        -e 's/0\.//' -e 's/1\./1/'
}

function inspectSink {
    wpctl inspect @DEFAULT_SINK@ |
        sed -E -n '/device.api/s/.*"(\w+)"/\1/p'
}

mapfile -t arr < <(inspectSink; getVolume)
if test "${arr[2]}" = "[MUTED]"
then
    echo " 🔇 "
    exit 0
fi

if test "${arr[0]}" = "bluez5"
then
    echo "🎧 ${arr[1]}%"
    exit 0
fi
if (( ${arr[1]} < 34 ))
then
    echo "🔈 ${arr[1]}%"
elif (( ${arr[0]} < 67 ))
then
    echo "🔉 ${arr[1]}%"
else
    echo "🔊 ${arr[1]}%"
fi
