#!/bin/bash

if test -z $1
then
    nvim $BASH_LIBRARY_PATH
elif test -x "$HOME/local/scripts/$1"
then
    nvim "$HOME/local/scripts/$1"
else
    # Using grep with '-n' to find the line number of the bash function
    # Then using Bash parameter expansion with '%' to extract the line number
    # and passing it to neovim.
    # Neovim accepts a line number prefixed with '+' and will open the file at the line number
    # The parameter expansion uses '%' to remove a suffix, which matches the pattern ':*'
    mapfile -td: match < <(grep -n "^function $1" $BASH_LIBRARY_PATH/*);
    nvim ${match[0]}  +${match[1]} -c "foldopen" -c "normal zz"
fi
