#!/bin/bash
# vim: ft=bash

patch=$1;
[[ $patch =~ [0-9]\.[0-9] ]];
commit=${BASH_REMATCH[0]};
git checkout $commit;
git apply $patch;
git add $patch
git commit -a -m "Patch: ${patch#*/}";
git checkout master;
git cherry-pick HEAD@{1}
