#!/bin/sh

JDTLS_HOME=$HOME/tools/jdtls
mkdir -p "$XDG_STATE_HOME"/jdtls/"$1"
java \
    -Declipse.application=org.eclipse.jdt.ls.core.id1 \
    -Dosgi.bundles.defaultStartLevel=4 \
    -Declipse.product=org.eclipse.jdt.ls.core.product \
    -Dlog.level=ALL \
    -Xmx1G \
    --add-modules=ALL-SYSTEM \
    --add-opens java.base/java.util=ALL-UNNAMED \
    --add-opens java.base/java.lang=ALL-UNNAMED \
    -javaagent:$HOME/dotfiles/lombok.jar \
    -jar $JDTLS_HOME/plugins/org.eclipse.equinox.launcher_*.jar \
    -configuration $JDTLS_HOME/config_linux \
    -data "$XDG_STATE_HOME"/jdtls/"$1"
