#!/usr/bin/perl

use strict;
use warnings;

my $themes_file = $ENV{"XDG_CONFIG_HOME"} ? $ENV{"XDG_CONFIG_HOME"} . "/themes" :
                                            $ENV{"HOME"} . ".config/themes";
open(my $in, "<", $themes_file) or die "Unable to open file $themes_file";
open(my $out, ">", "$themes_file.new") or die "Unable to create file $themes_file.new";
my @lines = <$in>;
if (@ARGV == 0) {
    for(@lines) { print /^(\w+);.*CURRENT/; }
    print "\n";
}
elsif ($ARGV[0] eq "list") {
    for(@lines) { print /^([\w\-_]+);/, "\n"; }
}
else {
    for(@lines) {
        s/;CURRENT.*//;
        s/$/;CURRENT/ if /$ARGV[0]/;
        print $out $_; 
    }
    close $in;
    close $out;
    rename "$themes_file.new", "$themes_file" or die "Can not rename $themes_file.new to $themes_file";
}
