import = [
	"~/.config/alacritty/kanagawa.toml",
    "~/.config/alacritty/local.toml"
]
[font]
[font.bold]
family = "IosevkaTerm Nerd Font"
style = "Bold"

[font.italic]
family = "IosevkaTerm Nerd Font"
style = "Italic"

[font.normal]
family = "IosevkaTerm Nerd Font"
style = "Regular"

# TODO: Remove the commented out schemes and put each in an individual file
# [schemes.gruvbox.bright]
# black = "0x928374"
# blue = "0x7daea3"
# cyan = "0x89b482"
# green = "0xa9b665"
# magenta = "0xd3869b"
# red = "0xea6962"
# white = "0xdfbf8e"
# yellow = "0xe3a84e"

# [schemes.gruvbox.normal]
# black = "0x282828"
# blue = "0x7daea3"
# cyan = "0x89b482"
# green = "0xa9b665"
# magenta = "0xd3869b"
# red = "0xea6962"
# white = "0xdfbf8e"
# yellow = "0xe78a4e"
#
# [schemes.gruvbox.primary]
# background = "0x282828"
# foreground = "0xdfbf8e"
#
# [schemes.papercolor.bright]
# black = "0x949494"
# blue = "0x4271ae"
# cyan = "0x3e999f"
# green = "0x718c00"
# magenta = "0x8959a8"
# red = "0xd7005f"
# white = "0x4d4d4c"
# yellow = "0xd75f00"
#
# [schemes.papercolor.cursor]
# cursor = "0x4d4d4c"
# text = "0xf3f3f3"
#
# [schemes.papercolor.normal]
# black = "0xffffff"
# blue = "0x4271ae"
# cyan = "0x3e999f"
# green = "0x718c00"
# magenta = "0x8959a8"
# red = "0xd7005f"
# white = "0x404040"
# yellow = "0xd75f00"
#
# [schemes.papercolor.primary]
# background = "0xffffff"
# foreground = "0x404040"
#
# [schemes.tokyo-night.bright]
# black = "0x444b6a"
# blue = "0x7da6ff"
# cyan = "0x0db9d7"
# green = "0xb9f27c"
# magenta = "0xbb9af7"
# red = "0xff7a93"
# white = "0xacb0d0"
# yellow = "0xff9e64"
#
# # [schemes.tokyo-night.normal]
# # black = "0x1a1b26"
# blue = "0x7aa2f7"
# cyan = "0x449dab"
# green = "0x9ece6a"
# magenta = "0xad8ee6"
# red = "0xf7768e"
# white = "0xa9b1d6"
# yellow = "0xe0af68"
#
# [schemes.tokyo-night.primary]
# background = "0x1a1b26"
# foreground = "0xa9b1d6"
#
# [[schemes.tokyo-night-day.indexed_colors]]
# color = "0xb15c00"
# index = 16
#
# [[schemes.tokyo-night-day.indexed_colors]]
# color = "0xc64343"
# index = 17
#
# [schemes.tokyo-night-day.bright]
# black = "0xa1a6c5"
# blue = "0x2e7de9"
# cyan = "0x007197"
# green = "0x587539"
# magenta = "0x9854f1"
# red = "0xf52a65"
# white = "0x3760bf"
# yellow = "0x8c6c3e"
#
# [schemes.tokyo-night-day.normal]
# black = "0xe1e2e7"
# blue = "0x2e7de9"
# cyan = "0x007197"
# green = "0x587539"
# magenta = "0x9854f1"
# red = "0xf52a65"
# white = "0x3760bf"
# yellow = "0x8c6c3e"
#
# # [schemes.tokyo-night-day.primary]
# background = "0xe1e2e7"
# foreground = "0x3760bf"
#
# [schemes.tokyo-night-storm.bright]
# black = "0x444b6a"
# blue = "0x7da6ff"
# cyan = "0x0db9d7"
# green = "0xb9f27c"
# magenta = "0xbb9af7"
# red = "0xff7a93"
# white = "0xacb0d0"
# yellow = "0xff9e64"
#
# [schemes.tokyo-night-storm.normal]
# black = "0x24283b"
# blue = "0x7aa2f7"
# cyan = "0x449dab"
# green = "0x9ece6a"
# magenta = "0xad8ee6"
# red = "0xf7768e"
# white = "0xa9b1d6"
# yellow = "0xe0af68"
#
# [schemes.tokyo-night-storm.primary]
# background = "0x24283b"
# foreground = "0xa9b1d6"
#

[scrolling]
history = 5000

[window]
title = "Alacritty"
startup_mode = "Windowed"

[window.padding]
x = 1
y = 0
