import = [
	"~/.config/alacritty/kanagawa.toml",
    "~/.config/alacritty/local.toml"
]
[scrolling]
history = 5000

[window]
title = "Alacritty"
startup_mode = "Windowed"

[window.padding]
x = 1
y = 0

[keyboard]
bindings = [
    { key = ",", mods = "Control", command = {program = "fonts", args = [ "prev" ]}},
    { key = ".", mods = "Control", command = {program = "fonts", args = [ "next" ]}}
]
