import = [
	"~/.config/alacritty/kanagawa.toml",
    "~/.config/alacritty/local.toml"
]
[font]
[font.bold]
family = "IosevkaTerm Nerd Font"
style = "Bold"

[font.italic]
family = "IosevkaTerm Nerd Font"
style = "Italic"

[font.normal]
family = "IosevkaTerm Nerd Font"
style = "Regular"


[scrolling]
history = 5000

[window]
title = "Alacritty"
startup_mode = "Windowed"

[window.padding]
x = 1
y = 0
